-- 244_contagem_hora_do_item.sql — A contagem passa a guardar QUANDO cada item foi contado.
--
-- ⚠️ NÃO é @cloud-only: `contagem_item` existe no edge e sincroniza desde a mig 243.
--
-- POR QUÊ
-- O ajuste da contagem é `contado − saldo_do_sistema`. Até aqui o "saldo do sistema" era
-- o snapshot congelado na ABERTURA da contagem — e isso só está certo se o item tiver
-- sido contado no instante da abertura.
--
-- Na operação real (descrita pelo dono) o inventário roda DURANTE o expediente:
--   • hambúrguer industrializado sai a cada venda E fica em dois lugares (câmara
--     frigorífica + freezer da chapa) — conta-se andando entre eles enquanto a chapa
--     consome;
--   • molho cheddar só sai na PRODUÇÃO, que roda fora do expediente — não corre risco
--     numa contagem diurna;
--   • parte dos lojistas conta com o expediente parado — risco zero.
--
-- Com a hora de cada item, o saldo de referência passa a ser o do INSTANTE em que
-- aquele item foi contado. Isso acerta os três casos com a mesma conta: item que se
-- move ganha a base do seu próprio momento, item que não se move tem base idêntica à
-- da abertura, e loja parada não tem movimento nenhum para diferenciar.

alter table contagem_item add column if not exists contado_em timestamptz;

-- ⚠️ SEM `create index` AQUI, de propósito.
-- A primeira versão desta migration criava um índice em `movimento_estoque` para o
-- recorte por tempo. Na nuvem isso ESTOUROU o tempo limite do editor e, como o arquivo
-- roda como UMA query (o `apply-sql.mjs` faz um único `client.query`, e o SQL Editor do
-- Supabase idem), a falha do índice desfez a transação inteira — inclusive o
-- `add column` acima. O resultado era pior que um erro: a migration "passava" sem
-- reclamar e a coluna simplesmente não existia.
--
-- O índice também não é necessário: o da mig 216, `(tenant_id, item_id)` INCLUDE
-- (tipo, quantidade), já restringe ao item exato — o filtro `created_at <= t` corre
-- sobre o conjunto pequeno que sobra. Se um dia a contagem ficar lenta em loja grande,
-- o índice entra SOZINHO e com `concurrently` (que não pode dividir arquivo com outro
-- comando, porque não roda dentro de transação):
--
--   create index concurrently if not exists idx_movimento_estoque_item_tempo
--     on movimento_estoque (tenant_id, item_id, created_at);
--
-- REGRA que fica: comando que pode DEMORAR (índice em tabela grande, backfill) não
-- divide arquivo com ALTER — senão derruba o ALTER junto.
